openapi: 3.2.0
info:
  title: Ingress Platform Composer Feature Flag API
  version: 1.0.0
servers:
- url: https://rls.congacloud.com/api/ingress
security:
- JWT: []
tags:
- name: PlatformComposerFeatureFlag
paths:
  /v1/FeatureFlags/{featureFlagName}:
    get:
      tags:
      - PlatformComposerFeatureFlag
      summary: Evaluate PlatformComposer feature flag for the given Salesforce Org Id
      operationId: PlatformComposerFeatureFlag_Get
      parameters:
      - name: featureFlagName
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        '200':
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
      security:
      - JWT: []
components:
  securitySchemes:
    JWT:
      type: apiKey
      description: Provide oauth authentication
      name: Authorization
      in: header
